name: MLOps CI/CD Pipeline

on:
  push:
    branches:
      - main
jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Linter
        run: black .

  test:
    runs-on: ubuntu-latest
    needs: lint  # This job will only run if 'lint' is successful
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Test Dependencies
        run: pip install pytest pytest-cov

      - name: Run Unit Tests
        run: pytest tests/

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Train Model
        run: python mlflow_train.py

      - name: Deploy Model
        run: python session3/train.py

      - name: Build Docker Image
        run: docker build -t iris_rf_model session3
      
      - name: Save Docker image
        run: docker save -o iris_rf_model.tar iris_rf_model            

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: iris_artifact
          path: iris_rf_model.tar
      
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: iris_artifact
          path: /opt/iris_rf_model.tar
