name: Group 89 MLOPS Assignment 1

on:
  [workflow_dispatch]
jobs:

  lint: # check for code quality/formatting

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Linter
        run: black .

        
  ingestion:
      runs-on: ubuntu-latest
      needs: lint  # This job ingest data 
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Install Dependencies
          run: pip install -r requirements.txt
    
        - name: Run Ingestion job
          run: python ingest.py
          
        - name: Run Data cleaning job
          run: python clean.py
          

  test:
      runs-on: ubuntu-latest
      needs: ingestion  # This job will check  test coverage for data quality
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Install Dependencies
          run: pip install -r requirements.txt
    
        - name: check clean job
          run: pytest test_clean.py
          
        - name: check Dataset job
          run: pytest test_dataset.py

  train:
      runs-on: ubuntu-latest
      needs: ingestion  # This job will train the ML model
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Install Dependencies
          run: pip install -r requirements.txt
    
        - name: Run Ingestion job
          run: python ingest.py
          
        - name: Run Data cleaning job
          run: python clean.py
          
        - name: Run training job
          run: python train.py
          
        - name: Run Prediction job
          run: python predict.py

  deploy:
    runs-on: ubuntu-latest
    needs: train # This job will build and dpeloy the model as a docker image in a docker hub repo

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt


      - name: Build Docker Image
        run: docker build -t girish1808/group89:latest .

      - name: Push image to docker hub
        run: |
          docker login -u girish1808 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push girish1808/group89:latest
