name: MLOps CI/CD Pipeline

on:
  [workflow_dispatch]
  # push:
  #   branches:
  #     - main
jobs:

  lint:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Linter
        run: black .

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint  # This job will only run if 'lint' is successful
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Install Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.10"
      
  #     - name: Install Dependencies
  #       run: pip install -r requirements.txt

  #     - name: Run Unit Tests
  #       run: python test.py
        
  train:
      runs-on: ubuntu-latest
      needs: lint  # This job will only run if 'lint' is successful
      steps:
        - name: Checkout Code
          uses: actions/checkout@v3
    
        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
        
        - name: Install Dependencies
          run: pip install -r requirements.txt
    
        - name: Run Unit Tests
          run: python src/ingest.py
          
        - name: Run Unit Tests
          run: python src/clean.py
          
        - name: Run Unit Tests
          run: python src/train.py
          
        - name: Run Unit Tests
          run: python src/predict.py
          
  deploy:
    runs-on: ubuntu-latest
    needs: train

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: pip install -r requirements.txt


      - name: Build Docker Image
        run: docker build -t girish1808/group89:latest .

      - name: Push image to docker hub
        run: |
          docker login -u girish1808 -p ${{ secrets.DOCKER_HUB_TOKEN }}
          docker push girish1808/group89:latest
      
      
      # - name: Save Docker image
      #   run: docker save -o iris_rf_model.tar iris_rf_model            

      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: iris_artifact
      #     path: iris_rf_model.tar
      
      # - name: Download Artifact
      #   uses: actions/download-artifact@v3
      #   with:
      #     name: iris_artifact
      #     path: /opt/iris_rf_model.tar
